default: &default
  adapter: postgresql
  host: localhost
  port: <%= ENV['PGPORT'].presence || '5432' %>
  pool: 3
  encoding: unicode
  username: <%= ENV['DB_USER'].presence || ENV['PGUSER'].presence || 'cider-ci' %>
  password: <%= ENV['DB_PASSWORD'].presence || ENV['PGPASSWORD'].presence || 'cider-ci' %>
  database: <%= ENV['DB_NAME'].presence || ENV['PGDATABASE'].presence || 'cider-ci_v5' %>
  variables:
    statement_timeout: 3000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default


