development:
  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'].presence || 'rails-secret-key-base-secret' %>

test:
  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'].presence || 'rails-secret-key-base-secret' %>

production:
  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'].presence || 'rails-secret-key-base-secret' %>

