default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 3
  database: 'cider-ci_test_{{CIDER_CI_TRIAL_ID}}'
  username: '<%= ENV['PGUSER'] %>'
  password: '<%= ENV['PGPASSWORD'] %>'
  port: '<%= ENV['PGPORT'] %>'
  variables:
    statement_timeout: 3000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
