jobs:
  assets:
    name: Assets
    run-on:
    - type: branch
      include-match: ^.*$
    task-defaults:
      git_options:
        submodules:
          clone: True
      environment-variables:
          RAILS_ENV: production
    tasks:
      assets_present:
        name: Assets are there?
        body: |
          set -eux
          test -f public/assets/application*js
      assets_up_to_date:
        name: Assets are up to date?
        _cider-ci_include: 'cider-ci/shared/rails-defaults.yml'
        scripts:
          test:
            start-when:
            - script: bundle
            - script: create-database
            body: |
              #!/usr/bin/env bash
              set -euo pipefail
              ./bin/rake assets:precompile
              cd public/assets
              git diff --stat --exit-code -- *
