jobs:
  assets:
    name: Assets
    run_when:
      on_any_branch:
        type: branch
        include_match: ^.*$
    task_defaults:
      git_options:
        submodules:
          include_match: '^.*$'
      environment_variables:
          RAILS_ENV: production
    tasks:
      assets_present:
        name: Assets are there?
        body: |
          #!/usr/bin/env bash
          set -euo pipefail
          test -f public/assets/application*js
      assets_up_to_date:
        name: Assets are up to date?
        include: 'cider-ci/shared/rails-defaults.yml'
        scripts:
          test:
            start_when:
              bundled:
                script_key: bundle
            start_when:
              database_created:
                script_key: create-database
            body: |
              #!/usr/bin/env bash
              set -euo pipefail
              bundle exec rake assets:precompile
              cd public/assets
              git diff --stat --exit-code -- *
