jobs:

  code-checks:

    name: Code Checks

    description: |
      Run static checks and metrics: complexity, duplicaiont, code format.

    run_when:
      on_any_branch:
        type: branch
        include_match: ^.*$

    context:

      task_defaults:

        eager_trials: 1
        max_trials: 2
        traits:
          linux: true
          rbenv: true
          ruby: true

        environment_variables:
          RAILS_ENV: test
          LANG: "en_US.UTF-8"

        scripts:
          bundle:
            exclusive_executor_resource: rbenv
            timeout: 10 Minutes
            body: |
              #!/usr/bin/env bash
              set -euo pipefail
              cd integration-tests
              rm .bundle/config
              bundle

          test:
            start_when:
              bundled:
                script_key: bundle

      tasks:

        code_complexity:
          name: Code complexity with flog
          scripts:
            test:
              body: bundle exec cider-ci_flog -l 120 app/ lib/

        code_similarity:
          name: Code similarity with flay
          scripts:
            test:
              body: bundle exec cider-ci_flay -m 164 app/ lib/

        lint_ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: bundle exec rubocop
