jobs:

  tests:

    name: Tests

    description: |
      Run specs under MRI.

    run_when:
      on_any_branch:
        type: branch
        include_match: ^.*$

    context:

      script_defaults:
        timeout: 5 Minutes

      task_defaults:

        include: 'cider-ci/shared/rails-defaults.yml'

        environment_variables:
          RAILS_ENV: test
          LANG: "en_US.UTF-8"

        scripts:
          test:
            start_when:
              bundled:
                script_key: bundle
              database_created:
                script_key: create-database
            body: |
              #!/usr/bin/env bash
              source database/bin/pg_env
              bundle exec rspec $CIDER_CI_TASK_FILE

        traits: {}

      generate_tasks:
        include_match: spec\/.*_spec.rb

